// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 10);
user_pref("app.normandy.user_id", "7fd8939d-c973-4fb3-9c74-5107ecb18d38");
user_pref("app.shield.optoutstudies.enabled", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1638239334);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1638238734);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1638239094);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1638321803);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1638238854);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1638239214);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1638238762);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1638239454);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 29362);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1638238704);
user_pref("browser.laterrun.bookkeeping.sessionCount", 2);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 96);
user_pref("browser.newtabpage.activity-stream.impressionId", "{568d1314-4e5a-4356-8ee7-49ab2f1ba380}");
user_pref("browser.newtabpage.activity-stream.improvesearch.topSiteSearchShortcuts.havePinned", "amazon");
user_pref("browser.newtabpage.pinned", "[{\"url\":\"https://amazon.com\",\"label\":\"@amazon\",\"searchTopSite\":true}]");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1638321805560");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1638323611560");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1638321806169");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1638343406169");
user_pref("browser.search.region", "JP");
user_pref("browser.search.useDBForOrder", true);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20210706194121");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1638321803");
user_pref("browser.slowStartup.averageTime", 25709);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20210706194121");
user_pref("browser.startup.homepage_override.mstone", "78.12.0");
user_pref("browser.startup.lastColdStartupCheck", 1638321802);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1638238715789");
user_pref("distribution.iniFile.exists.appversion", "78.12.0");
user_pref("distribution.iniFile.exists.value", false);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("dom.push.userAgentID", "b4e106be8775460e87ae2b9faa26deb6");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 32);
user_pref("extensions.getAddons.cache.lastUpdate", 1638239334);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20210706194121");
user_pref("extensions.lastAppVersion", "78.12.0");
user_pref("extensions.lastPlatformVersion", "78.12.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"directory\":\"{eb755423-4f43-4580-ab8c-428c99dac698}\",\"addons\":{\"proxy-failover@mozilla.com\":{\"version\":\"1.0.1\"}}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.doh-rollout@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"c5f80cb8-89db-482d-9d1a-acbfb4dd363a\",\"formautofill@mozilla.org\":\"6b77f3ea-04c2-482e-870e-cb8492ee35d1\",\"screenshots@mozilla.org\":\"262779fc-2d44-414f-ac99-5ee8981fb987\",\"webcompat-reporter@mozilla.org\":\"d05e7bb8-3b8b-4225-896d-422f1cd4ac36\",\"webcompat@mozilla.org\":\"11538a1a-d10d-4d5a-bd69-eb7fab6bb9f3\",\"default-theme@mozilla.org\":\"73e379fa-6543-493f-b25d-2a0b3b186bd7\",\"google@search.mozilla.org\":\"edde2acc-01c7-4e14-bfee-4b0f9d05d69c\",\"wikipedia@search.mozilla.org\":\"ddc146a1-4248-403c-8851-c783ee83120c\",\"yahoo-jp-auctions@search.mozilla.org\":\"a6171fcd-6df8-4039-aee2-2dd695447dd6\",\"bing@search.mozilla.org\":\"4ddcaaf5-c7b8-4575-b892-b4c08de1db9c\",\"rakuten@search.mozilla.org\":\"f21b4fee-bcec-4242-98a6-8a8b4b589a1c\",\"yahoo-jp@search.mozilla.org\":\"792a2901-4d85-4a2d-b4a5-b5c4847d0bad\",\"ddg@search.mozilla.org\":\"b28eaea1-c782-4eb6-941b-33c09528ee36\",\"oshiete-goo@search.mozilla.org\":\"1b44ede1-0ce6-4b8d-bda4-261b45e97288\",\"amazon@search.mozilla.org\":\"cdcb1275-9e63-449e-9191-b99b3b01ada8\",\"proxy-failover@mozilla.com\":\"01ef49c0-b9e5-47d4-a3ba-318cb9e54fd4\"}");
user_pref("idle.lastDailyNotification", 1638239466);
user_pref("media.gmp-manager.buildID", "20210706194121");
user_pref("media.gmp-manager.lastCheck", 1638238922);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.database.lastMaintenance", 1638239466);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.purge_trackers.date_in_cookie_database", "0");
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.remote_settings.crlite_filters.checked", 1638239215);
user_pref("security.remote_settings.intermediates.checked", 1638239215);
user_pref("security.sandbox.content.tempDirSuffix", "d396afc1-3906-480e-9d83-561c2efa549f");
user_pref("security.sandbox.plugin.tempDirSuffix", "1b1e8349-085f-4b9d-9f63-26ab107ece7b");
user_pref("services.blocklist.addons-mlbf.checked", 1638321803);
user_pref("services.blocklist.gfx.checked", 1638321803);
user_pref("services.blocklist.plugins.checked", 1638321803);
user_pref("services.settings.clock_skew_seconds", 0);
user_pref("services.settings.last_etag", "\"1638306000630\"");
user_pref("services.settings.last_update_seconds", 1638321803);
user_pref("services.settings.main.anti-tracking-url-decoration.last_check", 1638321803);
user_pref("services.settings.main.cfr.last_check", 1638321803);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1638321803);
user_pref("services.settings.main.hijack-blocklists.last_check", 1638321803);
user_pref("services.settings.main.language-dictionaries.last_check", 1638321803);
user_pref("services.settings.main.normandy-recipes-capabilities.last_check", 1638321803);
user_pref("services.settings.main.public-suffix-list.last_check", 1638321803);
user_pref("services.settings.main.search-config.last_check", 1638321803);
user_pref("services.settings.main.search-default-override-allowlist.last_check", 1638321803);
user_pref("services.settings.main.sites-classification.last_check", 1638321803);
user_pref("services.settings.main.tippytop.last_check", 1638321803);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1638321803);
user_pref("services.settings.main.whats-new-panel.last_check", 1638321803);
user_pref("services.settings.security.onecrl.checked", 1638239215);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1638239466);
user_pref("toolkit.startup.last_success", 1638321778);
user_pref("toolkit.telemetry.cachedClientID", "c0ffeec0-ffee-c0ff-eec0-ffeec0ffeec0");
user_pref("toolkit.telemetry.previousBuildID", "20210706194121");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
